# Generated by Django 2.1.7 on 2019-05-13 17:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('city', models.TextField()),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'venues',
                'managed': True,
            },
        ),
    ]
