# Generated by Django 2.1.7 on 2019-05-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20190519_1126'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='images',
            field=models.ManyToManyField(to='images.Image'),
        ),
    ]
