# Generated by Django 2.1.7 on 2019-05-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_id',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
