# Generated by Django 2.1.7 on 2019-05-13 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sports', '__first__'),
        ('venues', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('event_start', models.DateTimeField()),
                ('event_stop', models.DateTimeField()),
                ('host_id', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('sport_id', models.OneToOneField(db_column='sport_id', on_delete=django.db.models.deletion.DO_NOTHING, to='sports.Sport')),
                ('venue_id', models.OneToOneField(db_column='venue_id', on_delete=django.db.models.deletion.DO_NOTHING, to='venues.Venue')),
            ],
            options={
                'db_table': 'events',
                'managed': True,
            },
        ),
    ]
