# Generated by Django 2.1.7 on 2019-05-26 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190526_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='sport_id',
            field=models.ForeignKey(db_column='sport_id', on_delete=django.db.models.deletion.DO_NOTHING, to='sports.Sport'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_id',
            field=models.ForeignKey(db_column='venue_id', on_delete=django.db.models.deletion.DO_NOTHING, to='venues.Venue'),
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='event_id',
            field=models.OneToOneField(db_column='event_id', on_delete=django.db.models.deletion.DO_NOTHING, to='events.Event'),
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='user_id',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
