# Generated by Django 2.1.7 on 2019-05-31 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20190526_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendance',
            name='event_id',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.DO_NOTHING, to='events.Event'),
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='eventattendance',
            unique_together={('event_id', 'user_id')},
        ),
    ]
