# Generated by Django 2.1.7 on 2019-03-25 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.TextField()),
            ],
            options={
                'db_table': 'images',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('venue_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_id', models.OneToOneField(db_column='image_id', on_delete=django.db.models.deletion.DO_NOTHING, to='images.Image')),
                ('venue_id', models.OneToOneField(db_column='venue_id', on_delete=django.db.models.deletion.DO_NOTHING, to='venues.Venue')),
            ],
        ),
    ]
