# Generated by Django 2.1.7 on 2019-05-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venueimage',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='venueimage',
            name='venue_id',
        ),
        migrations.DeleteModel(
            name='VenueImage',
        ),
    ]
